### ISSUE TITLE
retained publish.mqtt messages

### ISSUE THREAD

**Issue by bertca** [ridiekel/jeletask#2]
Ok. Second question. 
Whenever I restart my Home Assistant, al the teletask mqtt devices become unavailable. I have to restart the jeletask package too in order to get them back.
As far as I can see is this because the jeletask mqtt.publish messages have no retain flag set. My Jeletask and Home Assistant are running on different devices, so this might give the problem. When they are running on the same device, both might be restarted...
Is there an option to get the retain flag set to the publish.mqtt messages?

Thanks again for the work delivered to get this done...

**Comment by VNDCK** [comment]
Hey! I Also have this problem. Got it fixed by restarting the Jeletask container with an automation.. if it can be fixed with a flag, that would be great :).
