### ISSUE TITLE
GENMOOD displayed as switch in HA

### ISSUE THREAD

**Issue by claesmathias** [ridiekel/jeletask#23]
I believe the better is to display the GENMOOD "Gaan slapen" as a scene in HA

![Screenshot 2022-10-11 at 10 58 39](https://user-images.githubusercontent.com/1142852/195047010-d4f848ce-a5b9-45b5-81e6-41c36bf1ee4b.png)

**Comment by SanderM2** [comment]
Ps: if you prefer to set auto discovery to a HA scene you can already do so by adding ' "hatype": "scene" ' to your config.json entries. ( It will force the HA auto discovery to 'scene' instead of the default 'switch'.)

**Comment by claesmathias** [comment]
Great thanks, can we add "hatype" to the documentation ?

**Comment by ridiekel** [comment]
This is now documented
