### ISSUE TITLE
State dimmer

### ISSUE THREAD

**Issue by claesmathias** [ridiekel/jeletask#30]
I have some problems with homebridge mqttthing library only accepting one possible getOn and setOn value. Would it be possible to not go to 100% when setting the ON, but to PREVIOUS_STATE? If we want 100%, we can set the brightness.

**Comment by claesmathias** [comment]
I found out we don't need to use anymore the state value, so I believe I can close this one.

**Comment by ridiekel** [comment]
If it would become an issue again, just let me know, then I will look into it
