### ISSUE TITLE
Detailed Installation

### ISSUE THREAD

**Issue by LtPixel** [ridiekel/jeletask#35]
Hello Everyone!

I've been using the (HACS) "Teletask Integration for Home Assistant" for the last 8 months. I've been a happy customer, as it enabled me to integrate my (Teletask) lights into Home Assistant. 💡 The integration is however limited, hence I stumbled on this gem. 💎 Thanks @ridiekel. 👍

As this installation is a different ball game, I'm planning to write an extensive step-by-step configration guide. 🎯 I've already setup a virtual machine and successfully tested the installation (Ubuntu, Samba, Docker and Jeletask). 🤯 The next steps is my final build (on dedicated hardware), which I'll use to document the build. 🚀

Let me know if there are any tips and tricks you would like me to include. 🤔

At this point, the things that aren't entirely clear to me (still need to do some research)...
* What is the purpose of the Additional HA config file? Why would I need it?
* What is the correct procedure for changing the configuration file in regards to the Docker container? If I add lights, what would be the correct procedure after changing the configuration file?

Thanks in advance. 😉 * And @ridiekel, if you like the final guide... we could publish it here.

**Comment by LtPixel** [comment]
-

**Comment by ridiekel** [comment]
Hi,

Thanks for taking the effort of writing some docs for this project. Always interested in the result. If you send the docs, I can look into reviewing them.
