### ISSUE TITLE
HA Switches get disabled 

### ISSUE THREAD

**Issue by claesmathias** [ridiekel/jeletask#8]
I have to relaunch the container to trigger re-activation of the switches in HA (auto-discovery). On the other hand my air-conditioners (MQTT [airCon](https://github.com/deiger/AirCon)) keep their functionality using HA auto discovery.

![Screenshot 2022-09-09 at 17 41 14](https://user-images.githubusercontent.com/1142852/189389029-3c699ae1-5229-4bbd-ac78-5bd69203b082.png)

**Comment by SanderM2** [comment]
Is this still an ongoing issue? If so, which version of jeletask are you running?

**Comment by ridiekel** [comment]
Can youo please check with 4.1.0?
