### ISSUE TITLE
No HA auto-discovery of temperature sensors

### ISSUE THREAD

**Issue by claesmathias** [ridiekel/jeletask#9]
Temperature sensors are not visible after HA auto-discovery. 

`    "SENSOR": [
      {
        "number": 19,
        "description": "Temperature Sensor",
        "type": "TEMPERATURE"
      }`

**Comment by SanderM2** [comment]
I think only dimmers and relays are supported for autodiscovery at the moment.
If I'm not mistaken, @ridiekel is working on HA auto discovery for motors.

HA autodiscovery for other items is probably on his todo list already.

**Comment by ridiekel** [comment]
This should be fixed in 4.1.0, can you please confirm?

**Comment by ridiekel** [comment]
Fixed since 4.1.0
